{
  try {
    onlyNull.validate("Not a null value");
    fail("expected onlyNull validator to fail with an exception");
  }
 catch (  Validator.InvalidValueException ex) {
    assertEquals("Only null accepted",ex.getMessage());
  }
  try {
    notNull.validate("Not a null value");
  }
 catch (  Validator.InvalidValueException ex) {
    fail("notNull should not throw exception for \"Not a null value\"");
  }
}
