{
  if (!exceptionsDuringCachePopulation.isEmpty()) {
    Throwable[] causes=new Throwable[exceptionsDuringCachePopulation.size()];
    exceptionsDuringCachePopulation.toArray(causes);
    exceptionsDuringCachePopulation.clear();
    throw new CacheUpdateException(this,"Error during Table cache update.",causes);
  }
}
